routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//login, reset-password, forgot-password, register
Auth::routes([
	'register'	=> false
]);

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group(['middleware' => 'auth'], function () {
	Route::resource('users', 'App\Http\Controllers\UserController', ['except' => ['edit']])->middleware('can:isAdmin');
	Route::post('users/password/{id}', 'App\Http\Controllers\UserController@updatePassword')->middleware('can:isAdmin')->name('update.password');

	Route::get('desa', 'App\Http\Controllers\DesaController@index')->name('desa');
	Route::post('desa/{id}', 'App\Http\Controllers\DesaController@update')->name('update.desa');

	Route::resource('penduduk', 'App\Http\Controllers\PendudukController');

	Route::resource('pindah-masuk', 'App\Http\Controllers\PindahMasukController');
	Route::get('pindah-masuk/print/{id}', 'App\Http\Controllers\PindahMasukController@print')->name('pindah-masuk.cetak');

	Route::resource('pindah-keluar', 'App\Http\Controllers\PindahKeluarController');
	Route::get('pindah-keluar/print/{id}', 'App\Http\Controllers\PindahKeluarController@print')->name('pindah-keluar.cetak');

	Route::resource('keluarga', 'App\Http\Controllers\KeluargaController');
	Route::post('keluarga/add-anggota/{id}', 'App\Http\Controllers\KeluargaController@tambahAnggota')->name('tambahAnggota');
	Route::delete('keluarga/remove-anggota/{id}', 'App\Http\Controllers\KeluargaController@removeAnggota')->name('removeAnggota');

	Route::get('/surat', 'App\Http\Controllers\SuratController@index')->name('surat.index');
	Route::get('/surat/create', 'App\Http\Controllers\SuratController@create')->name('surat.create');
	Route::post('/surat', 'App\Http\Controllers\SuratController@store')->name('surat.store');
	Route::get('/surat/print/{id}', 'App\Http\Controllers\SuratController@print')->name('surat.print');
	Route::delete('/surat/{id}', 'App\Http\Controllers\SuratController@destroy')->name('surat.delete');

	Route::get('/laporan', 'App\Http\Controllers\LaporanController@index')->name('laporan.index');

	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'App\Http\Controllers\ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'App\Http\Controllers\ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'App\Http\Controllers\ProfileController@password']);
});

Route::group(['middleware' => 'auth'], function () {
	Route::get('{page}', ['as' => 'page.index', 'uses' => 'App\Http\Controllers\PageController@index']);
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'role',
        'photo',
        'email_verified_at'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
// use App\Http\Requests\UserRequest;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Carbon\Carbon;

class UserController extends Controller
{
    /**
     * Display a listing of the users
     *
     * @param  \App\Models\User  $model
     * @return \Illuminate\View\View
     */
    public function index()
    {
        $data['users'] = User::where('id', '!=', auth()->user()->id)->get();
        return view('users.index', $data);
    }

    public function create()
    {
        return view('users.create');
    }

    public function show($id)
    {
        $data['user'] = User::where('id',$id)->first();
        return view('users.detail', $data);
    }

    public function store(Request $request)
    {
        $request->validate([
            'name'  => 'required',
            'email' => 'required|unique:users|email',
            'password'  => 'required|confirmed',
            'password_confirmation' => 'required',
            'role'  => 'required'
        ]);

        User::create([
            'name'  => $request->name,
            'email' => $request->email,
            'password'  => \Hash::make($request->password),
            'role'  => $request->role,
            'email_verified_at' => Carbon::now()
        ]);

        return redirect('users')->with('status', 'Pengguna baru telah dibuat!');
    }

    public function update(Request $request, $id)
    {
        $request->validate([
            'name'  => 'required',
            'email' => 'required|unique:users,email,'.$id.'|email',
            'role'  => 'required'
        ]);

        User::where('id', $id)->update([
            'name'  => $request->name,
            'email' => $request->email,
            'role'  => $request->role
        ]);

        return redirect('users')->with('status', 'Data pengguna telah diubah!');
    }

    public function destroy($id)
    {
        User::find($id)->delete();

        return redirect('users')->with('status', 'Pengguna telah dihapus!');
    }

    public function updatePassword(Request $request, $id)
    {
        $request->validate([
            'password'  => 'required|confirmed',
            'password_confirmation' => 'required'
        ]);

        User::where('id', $id)->update([
            'password'  => \Hash::make($request->password)
        ]);

        return redirect('users')->with('status', 'Password Telah Diubah!');
    }
}

resources/views/users/create.blade.php
@extends('layouts.app', [
    'class' => '',
    'elementActive' => 'users'
])

@section('content')
    <div class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="card-tools pull-right">
                            <a href="{{ route('users.index') }}" class="btn btn-info"><i class="nc-icon nc-minimal-left"></i> Kembali</a>
                        </div>
                        <h5 class="card-title">Tambah Pengguna</h5>
                    </div>
                    <form action="{{ route('users.store') }}" method="post">
                        @csrf
                    <div class="card-body border-top">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Nama <span class="text-danger">*</span></label>
                                    <input type="text" class="form-control @error('name') is-invalid @enderror" placeholder="Nama" value="{{ old('name') }}" name="name">
                                    @error('name')
                                        <div class="invalid-feedback">{{ $message }}</div>
                                    @enderror
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Email</label>
                                    <input type="email" class="form-control @error('email') is-invalid @enderror" placeholder="Email" value="{{ old('email') }}" name="email">
                                    @error('email')
                                        <div class="invalid-feedback">{{ $message }}</div>
                                    @enderror
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Password</label>
                                    <input type="password" name="password" class="form-control @error('password') is-invalid @enderror" placeholder="Password">
                                    @error('password')
                                        <div class="invalid-feedback">{{ $message }}</div>
                                    @enderror
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Konfirmasi Password</label>
                                    <input type="password" name="password_confirmation" class="form-control @error('password_confirmation') is-invalid @enderror" placeholder="Password">
                                    @error('password_confirmation')
                                        <div class="invalid-feedback">{{ $message }}</div>
                                    @enderror
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Hak Akses</label>
                                    <select name="role" class="custom-select @error('role') is-invalid @enderror">
                                        <option value="">-- Pilih --</option>
                                        <option value="kaur" @if(old('role') == 'kaur') selected @endif>Kaur</option>
                                        <option value="admin" @if(old('role') == 'admin') selected @endif>Admin</option>
                                    </select>
                                    @error('role')
                                        <div class="invalid-feedback">{{ $message }}</div>
                                    @enderror
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <button type="reset" class="btn btn-primary"><i class="nc-icon nc-refresh-69"></i> Reset</button>
                        <button type="submit" class="btn btn-success"><i class="nc-icon nc-tap-01"></i> Simpan</button>
                    </div>
                </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/users/detail.blade.php
@extends('layouts.app', [
    'class' => '',
    'elementActive' => 'users'
])

@section('content')
    <div class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="card-tools pull-right">
                            <a href="{{ route('users.index') }}" class="btn btn-info"><i class="nc-icon nc-minimal-left"></i> Kembali</a>
                        </div>
                        <h5 class="card-title">Detail Pengguna</h5>
                    </div>
                    <div class="card-body border-top">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="card">
                                    <form action="{{ route('users.update', $user->id) }}" method="POST">
                                        @method('PUT')
                                        @csrf
                                    <div class="card-body">
                                        <div class="form-group">
                                            <label for="">Name</label>
                                            <input type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name', $user->name) }}" placeholder="Nama">
                                            @error('name')
                                                <div class="invalid-feedback">{{ $message }}</div>
                                            @enderror
                                        </div>
                                        <div class="form-group">
                                            <label for="">Email</label>
                                            <input type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email', $user->email) }}" placeholder="Email">
                                            @error('email')
                                                <div class="invalid-feedback">{{ $message }}</div>
                                            @enderror
                                        </div>
                                        <div class="form-group">
                                            <label>Hak Akses</label>
                                            <select name="role" class="custom-select @error('role') is-invalid @enderror">
                                                <option value="">-- Pilih --</option>
                                                <option value="kaur" @if(old('role', $user->role) == 'kaur') selected @endif>Kaur</option>
                                                <option value="admin" @if(old('role',$user->role) == 'admin') selected @endif>Admin</option>
                                            </select>
                                            @error('role')
                                                <div class="invalid-feedback">{{ $message }}</div>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="card-footer">
                                        <button type="reset" class="btn btn-primary"><i class="nc-icon nc-refresh-69"></i> Reset</button>
                                        <button type="submit" class="btn btn-success"><i class="nc-icon nc-tap-01"></i> Simpan</button>
                                    </div>
                                </form>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="card">
                                    <div class="card-header">
                                        <h5 class="card-title">Update Password</h5>
                                    </div>
                                    <form action="{{ route('update.password', $user->id) }}" method="post">
                                        @csrf
                                        <div class="card-body border-top">
                                            <div class="form-group">
                                                <label>Password</label>
                                                <input type="password" name="password" class="form-control @error('password') is-invalid @enderror" placeholder="Password">
                                                @error('password')
                                                    <div class="invalid-feedback">{{ $message }}</div>
                                                @enderror
                                            </div>
                                            <div class="form-group">
                                                <label>Konfirmasi Password</label>
                                                <input type="password" name="password_confirmation" class="form-control @error('password_confirmation') is-invalid @enderror" placeholder="Password">
                                                @error('password_confirmation')
                                                    <div class="invalid-feedback">{{ $message }}</div>
                                                @enderror
                                            </div>
                                        </div>
                                        <div class="card-footer">
                                            <button type="submit" class="btn btn-warning"><i class="nc-icon nc-tap-01"></i> Update Password</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/users/index.blade.php
@extends('layouts.app', [
    'class' => '',
    'elementActive' => 'users'
])

@section('css')
<link rel="stylesheet" type="text/css" href="{{ asset('paper/css/sweetalert2.min.css')}}">
@endsection

@section('content')
<div class="content">
    <div class="row">
        <div class="col-md-12">
            @if (session('status'))
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                <strong>{{ session('status') }}.</strong>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
            @endif
            <div class="card">
                <div class="card-header">
                    <div class="card-tools pull-right"><a href="{{ route('users.create') }}" class="btn btn-success"><i class="nc-icon nc-simple-add"></i> Tambah Pengguna</a></div>
                    <h5 class="card-title">Data Pengguna</h5>
                </div>
                <div class="card-body border-top table-responsive">
                    <table class="table table-hover">
                        <thead class="text-primary">
                            <tr>
                                <th>Nama</th>
                                <th>Email</th>
                                <th>Akses</th>
                                <th>Aksi</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if ($users->count() > 0)
                                
                                @foreach ($users as $user)
                                    <tr>
                                        <td>{{ $user->name }}</td>
                                        <td>{{ $user->email }}</td>
                                        <td>{{ Str::ucfirst($user->role) }}</td>
                                        <td>
                                            <a href="{{ route('users.show', $user->id) }}" title="Detail" class="btn btn-info btn-sm"><i class="nc-icon nc-zoom-split"></i></a>
                                            <button onclick="confirmDelete({{ $user->id }})" title="Hapus" class="btn btn-danger btn-sm"><i class="nc-icon nc-simple-remove"></i></button>
                                        </td>
                                    </tr>
                                @endforeach
                            @else
                                <tr>
                                    <td colspan="4">
                                        <div class="alert alert-info" role="alert">
                                            Tidak ada data pengguna!
                                        </div>
                                    </td>
                                </tr>
                            @endif
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<form action="" method="post" id="delete-user">
    @method('DELETE')
    @csrf
</form>
@endsection

@push('scripts')
<script src="{{asset('paper/js/plugins/sweetalert2.all.min.js')}}"></script>
<script src="{{asset('paper/js/plugins/sweet-alerts.js')}}"></script>
<script>
    //Delete Confirmation
function confirmDelete(id) {
    Swal.fire({
          title: "Apa anda yakin?",
          text: "Anda tidak dapat mengembalikan data ini!",
          type: "warning",
          showCancelButton: true,
          cancelButtonText: "Tidak",
          confirmButtonText: "Ya, Hapus!",
          confirmButtonClass: "btn btn-danger",
          cancelButtonClass: "btn btn-primary ml-1",
          buttonsStyling: false
        }).then(function(result) {
          if (result.value) {
            $('#delete-user').attr('action', '/users/'+id);
            $('#delete-user').submit();
          }
        });
}
</script>
@endpush