routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//login, reset-password, forgot-password, register
Auth::routes([
	'register'	=> false
]);

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group(['middleware' => 'auth'], function () {
	Route::resource('users', 'App\Http\Controllers\UserController', ['except' => ['edit']])->middleware('can:isAdmin');
	Route::post('users/password/{id}', 'App\Http\Controllers\UserController@updatePassword')->middleware('can:isAdmin')->name('update.password');

	Route::get('desa', 'App\Http\Controllers\DesaController@index')->name('desa');
	Route::post('desa/{id}', 'App\Http\Controllers\DesaController@update')->name('update.desa');

	Route::resource('penduduk', 'App\Http\Controllers\PendudukController');

	Route::resource('pindah-masuk', 'App\Http\Controllers\PindahMasukController');
	Route::get('pindah-masuk/print/{id}', 'App\Http\Controllers\PindahMasukController@print')->name('pindah-masuk.cetak');

	Route::resource('pindah-keluar', 'App\Http\Controllers\PindahKeluarController');
	Route::get('pindah-keluar/print/{id}', 'App\Http\Controllers\PindahKeluarController@print')->name('pindah-keluar.cetak');

	Route::resource('keluarga', 'App\Http\Controllers\KeluargaController');
	Route::post('keluarga/add-anggota/{id}', 'App\Http\Controllers\KeluargaController@tambahAnggota')->name('tambahAnggota');
	Route::delete('keluarga/remove-anggota/{id}', 'App\Http\Controllers\KeluargaController@removeAnggota')->name('removeAnggota');

	Route::get('/surat', 'App\Http\Controllers\SuratController@index')->name('surat.index');
	Route::get('/surat/create', 'App\Http\Controllers\SuratController@create')->name('surat.create');
	Route::post('/surat', 'App\Http\Controllers\SuratController@store')->name('surat.store');
	Route::get('/surat/print/{id}', 'App\Http\Controllers\SuratController@print')->name('surat.print');
	Route::delete('/surat/{id}', 'App\Http\Controllers\SuratController@destroy')->name('surat.delete');

	Route::get('/laporan', 'App\Http\Controllers\LaporanController@index')->name('laporan.index');

	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'App\Http\Controllers\ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'App\Http\Controllers\ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'App\Http\Controllers\ProfileController@password']);
});

Route::group(['middleware' => 'auth'], function () {
	Route::get('{page}', ['as' => 'page.index', 'uses' => 'App\Http\Controllers\PageController@index']);
});

resources/views/layouts/navbars/auth.blade.php
<div class="sidebar" data-color="white" data-active-color="danger">
    <div class="logo">
        <a href="{{ route('home') }}" class="simple-text logo-mini">
            <div class="logo-image-small">
                {{-- <i class="nc-icon nc-circle-10"></i> --}}
                <img src="{{ asset('paper') }}/img/logo-small.png">
            </div>
        </a>
        <a href="{{ route('home') }}" class="simple-text logo-normal">
            SIADES
        </a>
    </div>
    <div class="sidebar-wrapper">
        <ul class="nav">
            <li class="{{ $elementActive == 'dashboard' ? 'active' : '' }}">
                <a href="{{ route('home') }}">
                    <i class="nc-icon nc-bank"></i>
                    <p>{{ __('Dashboard') }}</p>
                </a>
            </li>
            <li class="{{ $elementActive == 'penduduk' || $elementActive == 'keluarga' ? 'active' : '' }}" aria-expanded="{{ $elementActive == 'penduduk' || $elementActive == 'keluarga' ? true : false }}">
                <a data-toggle="collapse" aria-expanded="false" href="#kependudukan">
                    <i class="nc-icon nc-book-bookmark"></i>
                    <p>
                            Kependudukan
                        <b class="caret"></b>
                    </p>
                </a>
                <div class="collapse {{ $elementActive == 'penduduk' || $elementActive == 'keluarga' ? 'show' : '' }}" id="kependudukan">
                    <ul class="nav">
                        <li class="{{ $elementActive == 'penduduk' ? 'active' : '' }}">
                            <a href="{{ route('penduduk.index') }}">
                                <i class="nc-icon nc-badge"></i> Penduduk
                            </a>
                        </li>
                        <li class="{{ $elementActive == 'keluarga' ? 'active' : '' }}">
                            <a href="{{ route('keluarga.index') }}">
                                <i class="nc-icon nc-credit-card"></i> Keluarga
                            </a>
                        </li>
                    </ul>
                </div>
            </li>
            <li class="{{ $elementActive == 'masuk' || $elementActive == 'keluar' ? 'active' : '' }}">
                <a data-toggle="collapse" aria-expanded="false" href="#sirkulasi">
                    <i class="nc-icon nc-refresh-69"></i>
                    <p>
                            Sirkulasi
                        <b class="caret"></b>
                    </p>
                </a>
                <div class="collapse {{ $elementActive == 'masuk' || $elementActive == 'keluar' ? 'show' : '' }}"" id="sirkulasi">
                    <ul class="nav">
                        <li class="{{ $elementActive == 'masuk' ? 'active' : '' }}">
                            <a href="{{ route('pindah-masuk.index') }}">
                                <i class="nc-icon nc-calendar-60"></i>
                                Lahir / Pindah Masuk
                            </a>
                        </li>
                        <li class="{{ $elementActive == 'keluar' ? 'active' : '' }}">
                            <a href="{{ route('pindah-keluar.index') }}">
                                <i class="nc-icon nc-user-run"></i>
                                Wafat / Pindah Keluar
                            </a>
                        </li>
                    </ul>
                </div>
            </li>
            <li class="{{ $elementActive == 'surat' ? 'active' : '' }}">
                <a href="{{ route('surat.index') }}">
                    <i class="nc-icon nc-single-copy-04"></i>
                    <p>Surat</p>
                </a>
            </li>
            <li class="{{ $elementActive == 'laporan' ? 'active' : '' }}">
                <a href="{{ route('laporan.index') }}">
                    <i class="nc-icon nc-paper"></i>
                    <p>Laporan</p>
                </a>
            </li>
            @can('isAdmin')
            <li class="{{ $elementActive == 'desa' ? 'active' : '' }}">
                <a href="{{ route('desa') }}">
                    <i class="nc-icon nc-touch-id"></i>
                    <p>Indentitas Desa</p>
                </a>
            </li>
            @endcan
            <li class="{{ $elementActive == 'profile' ? 'active' : '' }}">
                <a href="{{ route('profile.edit') }}">
                    <i class="nc-icon nc-circle-10"></i>
                    <p>Profil</p>
                </a>
            </li>
            @can('isAdmin')
            <li class="{{ $elementActive == 'users' ? 'active' : '' }}">
                <a href="{{ route('users.index') }}">
                    <i class="nc-icon nc-single-02"></i>
                    <p>Pengguna</p>
                </a>
            </li>
            @endcan
        </ul>
    </div>
</div>