routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//login, reset-password, forgot-password, register
Auth::routes([
	'register'	=> false
]);

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group(['middleware' => 'auth'], function () {
	Route::resource('users', 'App\Http\Controllers\UserController', ['except' => ['edit']])->middleware('can:isAdmin');
	Route::post('users/password/{id}', 'App\Http\Controllers\UserController@updatePassword')->middleware('can:isAdmin')->name('update.password');

	Route::get('desa', 'App\Http\Controllers\DesaController@index')->name('desa');
	Route::post('desa/{id}', 'App\Http\Controllers\DesaController@update')->name('update.desa');

	Route::resource('penduduk', 'App\Http\Controllers\PendudukController');

	Route::resource('pindah-masuk', 'App\Http\Controllers\PindahMasukController');
	Route::get('pindah-masuk/print/{id}', 'App\Http\Controllers\PindahMasukController@print')->name('pindah-masuk.cetak');

	Route::resource('pindah-keluar', 'App\Http\Controllers\PindahKeluarController');
	Route::get('pindah-keluar/print/{id}', 'App\Http\Controllers\PindahKeluarController@print')->name('pindah-keluar.cetak');

	Route::resource('keluarga', 'App\Http\Controllers\KeluargaController');
	Route::post('keluarga/add-anggota/{id}', 'App\Http\Controllers\KeluargaController@tambahAnggota')->name('tambahAnggota');
	Route::delete('keluarga/remove-anggota/{id}', 'App\Http\Controllers\KeluargaController@removeAnggota')->name('removeAnggota');

	Route::get('/surat', 'App\Http\Controllers\SuratController@index')->name('surat.index');
	Route::get('/surat/create', 'App\Http\Controllers\SuratController@create')->name('surat.create');
	Route::post('/surat', 'App\Http\Controllers\SuratController@store')->name('surat.store');
	Route::get('/surat/print/{id}', 'App\Http\Controllers\SuratController@print')->name('surat.print');
	Route::delete('/surat/{id}', 'App\Http\Controllers\SuratController@destroy')->name('surat.delete');

	Route::get('/laporan', 'App\Http\Controllers\LaporanController@index')->name('laporan.index');

	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'App\Http\Controllers\ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'App\Http\Controllers\ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'App\Http\Controllers\ProfileController@password']);
});

Route::group(['middleware' => 'auth'], function () {
	Route::get('{page}', ['as' => 'page.index', 'uses' => 'App\Http\Controllers\PageController@index']);
});

app/Models/Keluarga.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Keluarga extends Model
{
    use HasFactory;

    protected $table = 'keluarga';

    protected $guarded = ['id'];

    public function kepala()
    {
        return $this->hasOne('App\Models\Penduduk', 'id', 'kepala_keluarga');
    }
    
    public function anggota()
    {
        return $this->hasMany('App\Models\Penduduk','keluarga_id','id');
    }
}

app/Http/Controllers/KeluargaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Keluarga;
use App\Models\Penduduk;

class KeluargaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['keluarga'] = Keluarga::latest()->get();

        return view('keluarga.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['penduduks'] = Penduduk::where('aktif', '1')->where('keluarga_id', null)->get();

        return view('keluarga.create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'no_kk'     => 'required|numeric|digits:16|unique:keluarga',
            'kepala_keluarga'   => 'required',
            'ekonomi'       => 'required'
        ]);

        $save_keluarga = Keluarga::create([
            'no_kk' => $request->no_kk,
            'kepala_keluarga'   => $request->kepala_keluarga,
            'ekonomi'   => $request->ekonomi
        ]);

        if ($save_keluarga) {
            Penduduk::where('id', $request->kepala_keluarga)->update([
                'keluarga_id'   => $save_keluarga->id,
                'status_keluarga'   => 'Kepala Keluarga'
            ]);
        }

        return redirect('keluarga')->with('status', 'Data keluarga telah ditambahkan!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data['keluarga']   = Keluarga::where('id', $id)->with('kepala')->first();
        $data['penduduks']  = $data['penduduks'] = Penduduk::where('aktif', '1')->where('keluarga_id', null)->get();

        return view('keluarga.show', $data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function tambahAnggota(Request $request, $id)
    {
        $request->validate([
            'penduduk'  => 'required',
            'status_keluarga'   => 'required'
        ]);

        Penduduk::where('id', $request->penduduk)->update([
            'keluarga_id'   => $id,
            'status_keluarga'   => $request->status_keluarga
        ]);

        return redirect()->back()->with('status', 'Anggota keluarga telah ditambahkan!');
    }

    public function removeAnggota($id)
    {
        Penduduk::where('id', $id)->update([
            'keluarga_id'   => null,
            'status_keluarga'   => null
        ]);

        return redirect()->back()->with('status', 'Anggota keluarga telah dihapus!');
    }

    public function edit($id)
    {
        $data['keluarga'] = Keluarga::where('id', $id)->first();
        $data['penduduks'] = Penduduk::where('aktif', '1')->where('keluarga_id', null)->get();

        return view('keluarga.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'no_kk'     => 'required|numeric|digits:16|unique:keluarga,no_kk,'.$id,
            'kepala_keluarga'   => 'required',
            'ekonomi'       => 'required'
        ]);

        $keluarga = Keluarga::where('id', $id)->first();

        if ($keluarga->kepala_keluarga != $request->kepala_keluarga) {
            Penduduk::where('id', $keluarga->kepala_keluarga)->update([
                'keluarga_id'   => null,
                'status_keluarga' => null
            ]);

            Penduduk::where('id', $request->kepala_keluarga)->update([
                'keluarga_id'   => $id,
                'status_keluarga' => 'Kepala Keluarga'
            ]);
        }else{
            Penduduk::where('id', $request->kepala_keluarga)->update([
                'keluarga_id'   => $id,
                'status_keluarga' => 'Kepala Keluarga'
            ]);
        }

        Keluarga::where('id', $id)->update([
            'no_kk' => $request->no_kk,
            'kepala_keluarga' => $request->kepala_keluarga,
            'ekonomi'   => $request->ekonomi
        ]);

        return redirect('keluarga')->with('status', 'Data keluarga telah diubah!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Penduduk::where('keluarga_id', $id)->update([
            'keluarga_id'   => null,
            'status_keluarga'   => null
        ]);

        Keluarga::where('id', $id)->delete();

        return redirect('keluarga')->with('status', 'Keluarga telah dihapus!');
    }
}

resources/views/keluarga/create.blade.php
@extends('layouts.app', [
    'class' => '',
    'elementActive' => 'keluarga'
])

@section('content')
    <div class="content">
        <div class="row">
            <div class="col">
                <div class="card">
                    <div class="card-header">
                        <div class="card-tools pull-right">
                            <a href="{{ route('keluarga.index') }}" class="btn btn-info"><i class="nc-icon nc-minimal-left"></i> Kembali</a>
                        </div>
                        <h5 class="card-title">Tambah Keluarga</h5>
                    </div>
                    <form action="{{ route('keluarga.store') }}" method="POST">
                    @csrf
                        <div class="card-body">
                            <div class="row">
                                <div class="form-group col-md-4">
                                    <label for="">No. KK</label>
                                    <input type="text" class="form-control @error('no_kk') is-invalid @enderror" placeholder="Nomor Kartu Keluarga" name="no_kk" value="{{ old('no_kk') }}">
                                    @error('no_kk')
                                        <div class="invalid-feedback">
                                            {{ $message }}
                                        </div>
                                    @enderror
                                </div>
                                <div class="form-group col-md-4">
                                    <label for="">Kepala Keluarga</label>
                                    <select name="kepala_keluarga" class="custom-select @error('kepala_keluarga') is-invalid @enderror">
                                        <option value="">-- Pilih --</option>
                                        @foreach ($penduduks as $penduduk)
                                            <option value="{{ $penduduk->id }}" @if(old('kepala_keluarga') == $penduduk->id) selected @endif>{{ $penduduk->nama }}</option>
                                        @endforeach
                                    </select>
                                    @error('kepala_keluarga')
                                        <div class="invalid-feedback">
                                            {{ $message }}
                                        </div>
                                    @enderror
                                </div>
                                <div class="form-group col-md-4">
                                    <label for="">Status Ekonomi</label>
                                    <select name="ekonomi" class="custom-select @error('ekonomi') is-invalid @enderror">
                                        <option value="">-- Pilih --</option>
                                        <option value="Sangat Mampu" @if(old('ekonomi') == 'Sangat Mampu') selected @endif>Sangat Mampu</option>
                                        <option value="Cukup Mampu" @if(old('ekonomi') == 'Cukup Mampu') selected @endif>Cukup Mampu</option>
                                        <option value="Mampu" @if(old('ekonomi') == 'Mampu') selected @endif>Mampu</option>
                                        <option value="Tidak Mampu" @if(old('ekonomi') == 'Tidak Mampu') selected @endif>Tidak Mampu</option>
                                        <option value="Sangat Tidak Mampu" @if(old('ekonomi') == 'Sangat Tidak Mampu') selected @endif>Sangat Tidak Mampu</option>
                                        <option value="Lainnya" @if(old('ekonomi') == 'Lainnya') selected @endif>Lainnya</option>
                                    </select>
                                    @error('ekonomi')
                                        <div class="invalid-feedback">
                                            {{ $message }}
                                        </div>
                                    @enderror
                                </div>
                            </div>
                        </div>
                        <div class="card-footer">
                            <button type="reset" class="btn btn-primary"><i class="nc-icon nc-refresh-69"></i> Reset</button>
                            <button type="submit" class="btn btn-success"><i class="nc-icon nc-tap-01"></i> Simpan</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/keluarga/edit.blade.php
@extends('layouts.app', [
    'class' => '',
    'elementActive' => 'keluarga'
])

@section('content')
    <div class="content">
        <div class="row">
            <div class="col">
                <div class="card">
                    <div class="card-header">
                        <div class="card-tools pull-right">
                            <a href="{{ route('keluarga.index') }}" class="btn btn-info"><i class="nc-icon nc-minimal-left"></i> Kembali</a>
                        </div>
                        <h5 class="card-title">Edit Keluarga</h5>
                    </div>
                    <form action="{{ route('keluarga.update', $keluarga->id) }}" method="POST">
                    @csrf
                    @method('PUT')
                        <div class="card-body">
                            <div class="row">
                                <div class="form-group col-md-4">
                                    <label for="">No. KK</label>
                                    <input type="text" class="form-control @error('no_kk') is-invalid @enderror" placeholder="Nomor Kartu Keluarga" name="no_kk" value="{{ old('no_kk', $keluarga->no_kk) }}">
                                    @error('no_kk')
                                        <div class="invalid-feedback">
                                            {{ $message }}
                                        </div>
                                    @enderror
                                </div>
                                <div class="form-group col-md-4">
                                    <label for="">Kepala Keluarga</label>
                                    <select name="kepala_keluarga" class="custom-select @error('kepala_keluarga') is-invalid @enderror">
                                        <option value="{{ $keluarga->kepala->id }}">{{ $keluarga->kepala->nama }}</option>
                                        @foreach ($penduduks as $penduduk)
                                            <option value="{{ $penduduk->id }}" @if(old('kepala_keluarga', $keluarga->kepala_keluarga) == $penduduk->id) selected @endif>{{ $penduduk->nama }}</option>
                                        @endforeach
                                    </select>
                                    @error('kepala_keluarga')
                                        <div class="invalid-feedback">
                                            {{ $message }}
                                        </div>
                                    @enderror
                                </div>
                                <div class="form-group col-md-4">
                                    <label for="">Status Ekonomi</label>
                                    <select name="ekonomi" class="custom-select @error('ekonomi') is-invalid @enderror">
                                        <option value="">-- Pilih --</option>
                                        <option value="Sangat Mampu" @if(old('ekonomi', $keluarga->ekonomi) == 'Sangat Mampu') selected @endif>Sangat Mampu</option>
                                        <option value="Cukup Mampu" @if(old('ekonomi', $keluarga->ekonomi) == 'Cukup Mampu') selected @endif>Cukup Mampu</option>
                                        <option value="Mampu" @if(old('ekonomi', $keluarga->ekonomi) == 'Mampu') selected @endif>Mampu</option>
                                        <option value="Tidak Mampu" @if(old('ekonomi', $keluarga->ekonomi) == 'Tidak Mampu') selected @endif>Tidak Mampu</option>
                                        <option value="Sangat Tidak Mampu" @if(old('ekonomi', $keluarga->ekonomi) == 'Sangat Tidak Mampu') selected @endif>Sangat Tidak Mampu</option>
                                        <option value="Lainnya" @if(old('ekonomi', $keluarga->ekonomi) == 'Lainnya') selected @endif>Lainnya</option>
                                    </select>
                                    @error('ekonomi')
                                        <div class="invalid-feedback">
                                            {{ $message }}
                                        </div>
                                    @enderror
                                </div>
                            </div>
                        </div>
                        <div class="card-footer">
                            <button type="submit" class="btn btn-success"><i class="nc-icon nc-tap-01"></i> Simpan</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/keluarga/show.blade.php
@extends('layouts.app', [
    'class' => '',
    'elementActive' => 'keluarga'
])

@section('css')
<link rel="stylesheet" type="text/css" href="{{ asset('paper/css/sweetalert2.min.css')}}">
@endsection

@section('content')
    <div class="content">
        <div class="row">
            <div class="col">
                @if (session('status'))
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    <strong>{{ session('status') }}.</strong>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                @endif
                <div class="card">
                    <div class="card-header">
                        <div class="card-tools pull-right">
                            <a href="{{ route('keluarga.index') }}" class="btn btn-info"><i class="nc-icon nc-minimal-left"></i> Kembali</a>
                        </div>
                        <h5 class="card-title">Detail Keluarga</h5>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-4 form-group">
                                <label for="">No. KK</label>
                                <input type="text" class="form-control-plaintext" readonly value="{{ $keluarga->no_kk }}">
                            </div>
                            <div class="col-md-4 form-group">
                                <label for="">Kepala Keluarga</label>
                                <input type="text" class="form-control-plaintext" readonly value="{{ $keluarga->kepala->nama }}">
                            </div>
                            <div class="col-md-4 form-group">
                                <label for="">Ekonomi</label>
                                <input type="text" class="form-control-plaintext" readonly value="{{ $keluarga->ekonomi }}">
                            </div>
                        </div>
                        <div class="row border-top">
                            <div class="col-md-12">
                                <div class="card">
                                    <div class="card-header">
                                        <div class="card-tools pull-right">
                                            <button data-toggle="modal" data-target="#tambahAnggota" class="btn btn-sm btn-round btn-success"><i class="nc-icon nc-simple-add"></i> Tambah Anggota</a>
                                        </div>
                                        <h6 class="card-title">Anggota Keluarga</h6>
                                    </div>
                                    <div class="card-body border-top">
                                        <table class="table table-hover">
                                            <thead class="text-primary">
                                                <tr>
                                                    <th>#</th>
                                                    <th>NIK</th>
                                                    <th>Nama Lengkap</th>
                                                    <th>L/P</th>
                                                    <th>Status</th>
                                                    <th></th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @if ($keluarga->anggota->count() == 0)
                                                    <tr>
                                                        <td colspan="6">
                                                            <div class="alert alert-info" role="alert">
                                                                Tidak ada anggota!
                                                            </div>
                                                        </td>
                                                    </tr>
                                                @endif
                                                @foreach ($keluarga->anggota as $key => $anggota)
                                                    <tr>
                                                        <td>{{ $key+1 }}</td>
                                                        <td>{{ $anggota->nik }}</td>
                                                        <td>{{ $anggota->nama }}</td>
                                                        <td>{{ $anggota->jenis_kelamin }}</td>
                                                        <td>{{ $anggota->status_keluarga }}</td>
                                                        <td>
                                                            <a href="{{ route('penduduk.show', $anggota->id) }}" title="Detail" class="btn btn-info btn-sm"><i class="nc-icon nc-zoom-split"></i></a>
                                                            @if ($anggota->status_keluarga != 'Kepala Keluarga')
                                                            <button onclick="confirmDelete({{ $anggota->id }})" title="Hapus" class="btn btn-danger btn-sm"><i class="nc-icon nc-simple-remove"></i></button
                                                                
                                                            @endif
                                                        </td>
                                                    </tr>
                                                @endforeach
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="tambahAnggota" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Tambah Anggota</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form action="{{ route('tambahAnggota', $keluarga->id) }}" method="POST">
                    @csrf
                    <div class="modal-body">
                        <div class="form-group">
                            <label for="">Penduduk</label>
                            <select name="penduduk" class="custom-select @error('penduduk') is-invalid @enderror">
                                <option value="">-- Pilih --</option>
                                @foreach ($penduduks as $penduduk)
                                    <option value="{{ $penduduk->id }}" @if(old('penduduk') == $penduduk->id) selected @endif>{{ $penduduk->nik }} - {{ $penduduk->nama }}</option>
                                @endforeach
                            </select>
                            @error('penduduk')
                                <div class="invalid-feedback">{{ $message }}</div>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="">Status</label>
                            <select name="status_keluarga" class="custom-select @error('status_keluarga') is-invalid @enderror">
                                <option value="">-- Pilih --</option>
                                <option value="Suami" @if(old('status_keluarga') == 'Suami') selected @endif>Suami</option>
                                <option value="Istri" @if(old('status_keluarga') == 'Istri') selected @endif>Istri</option>
                                <option value="Anak" @if(old('status_keluarga') == 'Anak') selected @endif>Anak</option>
                                <option value="Menantu" @if(old('status_keluarga') == 'Menantu') selected @endif>Menantu</option>
                                <option value="Cucu" @if(old('status_keluarga') == 'Cucu') selected @endif>Cucu</option>
                                <option value="Orang Tua" @if(old('status_keluarga') == 'Orang Tua') selected @endif>Orang Tua</option>
                                <option value="Famili Lain" @if(old('status_keluarga') == 'Famili Lain') selected @endif>Famili Lain</option>
                                <option value="Pembantu" @if(old('status_keluarga') == 'Pembantu') selected @endif>Pembantu</option>
                                <option value="Lainnya" @if(old('status_keluarga') == 'Lainnya') selected @endif>Lainnya</option>
                            </select>
                            @error('status_keluarga')
                                <div class="invalid-feedback">{{ $message }}</div>
                            @enderror
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-danger" data-dismiss="modal"><i class="nc-icon nc-simple-remove"></i>Batal</button>
                        <button type="submit" class="btn btn-success"><i class="nc-icon nc-tap-01"></i> Simpan</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <form action="" method="post" id="delete-anggota">
        @method('DELETE')
        @csrf
    </form>
@endsection

@push('scripts')
@if($errors->any())
<script>
$('#tambahAnggota').modal({show: true});
</script>
@endif
<script src="{{asset('paper/js/plugins/sweetalert2.all.min.js')}}"></script>
<script src="{{asset('paper/js/plugins/sweet-alerts.js')}}"></script>
<script>
    //Delete Confirmation
function confirmDelete(id) {
    Swal.fire({
          title: "Apa anda yakin?",
          text: "Anda akan mengeluarkan anggota keluarga!",
          type: "warning",
          showCancelButton: true,
          cancelButtonText: "Tidak",
          confirmButtonText: "Ya, Hapus!",
          confirmButtonClass: "btn btn-danger",
          cancelButtonClass: "btn btn-primary ml-1",
          buttonsStyling: false
        }).then(function(result) {
          if (result.value) {
            $('#delete-anggota').attr('action', '/keluarga/remove-anggota/'+id);
            $('#delete-anggota').submit();
          }
        });
}
</script>
@endpush