routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//login, reset-password, forgot-password, register
Auth::routes([
	'register'	=> false
]);

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group(['middleware' => 'auth'], function () {
	Route::resource('users', 'App\Http\Controllers\UserController', ['except' => ['edit']])->middleware('can:isAdmin');
	Route::post('users/password/{id}', 'App\Http\Controllers\UserController@updatePassword')->middleware('can:isAdmin')->name('update.password');

	Route::get('desa', 'App\Http\Controllers\DesaController@index')->name('desa');
	Route::post('desa/{id}', 'App\Http\Controllers\DesaController@update')->name('update.desa');

	Route::resource('penduduk', 'App\Http\Controllers\PendudukController');

	Route::resource('pindah-masuk', 'App\Http\Controllers\PindahMasukController');
	Route::get('pindah-masuk/print/{id}', 'App\Http\Controllers\PindahMasukController@print')->name('pindah-masuk.cetak');

	Route::resource('pindah-keluar', 'App\Http\Controllers\PindahKeluarController');
	Route::get('pindah-keluar/print/{id}', 'App\Http\Controllers\PindahKeluarController@print')->name('pindah-keluar.cetak');

	Route::resource('keluarga', 'App\Http\Controllers\KeluargaController');
	Route::post('keluarga/add-anggota/{id}', 'App\Http\Controllers\KeluargaController@tambahAnggota')->name('tambahAnggota');
	Route::delete('keluarga/remove-anggota/{id}', 'App\Http\Controllers\KeluargaController@removeAnggota')->name('removeAnggota');

	Route::get('/surat', 'App\Http\Controllers\SuratController@index')->name('surat.index');
	Route::get('/surat/create', 'App\Http\Controllers\SuratController@create')->name('surat.create');
	Route::post('/surat', 'App\Http\Controllers\SuratController@store')->name('surat.store');
	Route::get('/surat/print/{id}', 'App\Http\Controllers\SuratController@print')->name('surat.print');
	Route::delete('/surat/{id}', 'App\Http\Controllers\SuratController@destroy')->name('surat.delete');

	Route::get('/laporan', 'App\Http\Controllers\LaporanController@index')->name('laporan.index');

	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'App\Http\Controllers\ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'App\Http\Controllers\ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'App\Http\Controllers\ProfileController@password']);
});

Route::group(['middleware' => 'auth'], function () {
	Route::get('{page}', ['as' => 'page.index', 'uses' => 'App\Http\Controllers\PageController@index']);
});

app/Models/Mutasi.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Mutasi extends Model
{
    use HasFactory;

    protected $table = 'mutasi';

    protected $guarded = ['id'];

    public function anggota()
    {
        return $this->hasOne('App\Models\Penduduk','id','penduduk_id');
    }
}

resources/views/mutasi/masuk/index.blade.php
@extends('layouts.app', [
    'class' => '',
    'elementActive' => 'masuk'
])

@section('css')
<link rel="stylesheet" type="text/css" href="{{ asset('paper/css/sweetalert2.min.css')}}">
@endsection

@section('content')
    <div class="content">
        <div class="row">
            <div class="col">
                @if (session('status'))
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    <strong>{{ session('status') }}.</strong>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                @endif
                <div class="card">
                    <div class="card-header">
                        <div class="card-tools pull-right"><a href="{{ route('pindah-masuk.create') }}" class="btn btn-success"><i class="nc-icon nc-simple-add"></i> Tambah Data</a></div>
                        <h5 class="card-title">Data Lahir/Pindah Masuk</h5>
                    </div>
                    <div class="card-body border-top">
                        <table class="table table-hover">
                            <thead class="text-primary">
                                <tr>
                                    <th>#</th>
                                    <th>NIK</th>
                                    <th>Nama</th>
                                    <th>L/P</th>
                                    <th>Jenis Mutasi</th>
                                    <th>Tgl Kejadian</th>
                                    <th>Aksi</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if ($penduduks->count() == 0)
                                    <tr>
                                        <td colspan="7">
                                            <div class="alert alert-info">Tidak ada data mutasi penduduk.</div>
                                        </td>
                                    </tr>
                                @else
                                    @foreach ($penduduks as $key => $penduduk)
                                        <tr>
                                            <td>{{ $key+1 }}</td>
                                            <td>{{ $penduduk->anggota->nik }}</td>
                                            <td>{{ $penduduk->anggota->nama }}</td>
                                            <td>{{ $penduduk->anggota->jenis_kelamin }}</td>
                                            <td>{{ $penduduk->jenis }}</td>
                                            <td>{{ date_format(date_create($penduduk->tanggal), 'd-m-Y') }}</td>
                                            <td>
                                                <!-- <a href="{{ route('pindah-masuk.cetak', $penduduk->id) }}" title="Cetak Surat" class="btn btn-success btn-sm"><i class="nc-icon nc-paper"></i></a> -->
                                                <a href="{{ route('pindah-masuk.show', $penduduk->id) }}" title="Detail" class="btn btn-info btn-sm"><i class="nc-icon nc-zoom-split"></i></a>
                                                <a href="{{ route('pindah-masuk.edit', $penduduk->id) }}" title="Edit" class="btn btn-warning btn-sm"><i class="nc-icon nc-ruler-pencil"></i></a>
                                                <button onclick="confirmDelete({{ $penduduk->id }})" title="Hapus" class="btn btn-danger btn-sm"><i class="nc-icon nc-simple-remove"></i></button>
                                            </td>
                                        </tr>
                                    @endforeach
                                @endif
                            </tbody>
                        </table>
                    </div>
                    
                </div>
            </div>
        </div>
    </div>

    <form action="" method="post" id="delete-penduduk">
        @method('DELETE')
        @csrf
    </form>
@endsection

@push('scripts')
<script src="{{asset('paper/js/plugins/sweetalert2.all.min.js')}}"></script>
<script src="{{asset('paper/js/plugins/sweet-alerts.js')}}"></script>
<script>
    //Delete Confirmation
function confirmDelete(id) {
    Swal.fire({
          title: "Apa anda yakin?",
          text: "Anda tidak dapat mengembalikan data ini!",
          type: "warning",
          showCancelButton: true,
          cancelButtonText: "Tidak",
          confirmButtonText: "Ya, Hapus!",
          confirmButtonClass: "btn btn-danger",
          cancelButtonClass: "btn btn-primary ml-1",
          buttonsStyling: false
        }).then(function(result) {
          if (result.value) {
            $('#delete-penduduk').attr('action', '/pindah-masuk/'+id);
            $('#delete-penduduk').submit();
          }
        });
}
</script>
@endpush

resources/views/mutasi/masuk/show.blade.php
@extends('layouts.app', [
    'class' => '',
    'elementActive' => 'masuk'
])

@section('content')
    <div class="content">
        <div class="row">
            <div class="col">
                <div class="card">
                    <div class="card-header">
                        <div class="card-tools pull-right">
                            <a href="{{ route('pindah-masuk.index') }}" class="btn btn-info"><i class="nc-icon nc-minimal-left"></i> Kembali</a>
                        </div>
                        <h5 class="card-title">Detail Data Mutasi</h5>
                    </div>
                    <div class="card-body border-top">
                        <div class="row mb-2">
                            <div class="col-md-4">
                                Nomor Induk Kependudukan (NIK)
                            </div>
                            <div class="col-md-8">
                                : <strong>{{ $penduduk->anggota->nik }}</strong>
                            </div>
                        </div>
                        <div class="row mb-2">
                            <div class="col-md-4">
                                Nama Lengkap
                            </div>
                            <div class="col-md-8">
                                : <strong>{{ $penduduk->anggota->nama }}</strong>
                            </div>
                        </div>
                        <div class="row mb-2">
                            <div class="col-md-4">
                                Alamat
                            </div>
                            <div class="col-md-8">
                                : <strong>{{ $penduduk->anggota->alamat_tinggal }}</strong>
                            </div>
                        </div>
                        <div class="row mb-2">
                            <div class="col-md-4">
                                Tempat, Tanggal Lahir
                            </div>
                            <div class="col-md-8">
                                : <strong>{{ $penduduk->anggota->tmp_lahir }}, {{ date_format(date_create($penduduk->anggota->tgl_lahir), 'd-m-Y') }}</strong>
                            </div>
                        </div>
                        <div class="row mb-2">
                            <div class="col-md-4">
                                Jenis Kelamin
                            </div>
                            <div class="col-md-8">
                                : <strong>{{ ($penduduk->anggota->jenis_kelamin == 'L') ? 'Laki-Laki' : 'Perempuan' }}</strong>
                            </div>
                        </div>
                        <div class="row mb-2">
                            <div class="col-md-4">
                                Agama
                            </div>
                            <div class="col-md-8">
                                : <strong>{{ $penduduk->anggota->agama }}</strong>
                            </div>
                        </div>
                        <div class="row mb-2">
                            <div class="col-md-4">
                                Golongan Darah
                            </div>
                            <div class="col-md-8">
                                : <strong>{{ $penduduk->anggota->gol_darah }}</strong>
                            </div>
                        </div>
                        <div class="row mb-2">
                            <div class="col-md-4">
                                Status Perkawinan
                            </div>
                            <div class="col-md-8">
                                : <strong>{{ $penduduk->anggota->status_nikah }}</strong>
                            </div>
                        </div>
                        <div class="row mb-2">
                            <div class="col-md-4">
                                Pendidikan
                            </div>
                            <div class="col-md-8">
                                : <strong>{{ $penduduk->anggota->pendidikan }}</strong>
                            </div>
                        </div>
                        <div class="row mb-2">
                            <div class="col-md-4">
                                Pekerjaan
                            </div>
                            <div class="col-md-8">
                                : <strong>{{ $penduduk->anggota->pekerjaan }}</strong>
                            </div>
                        </div>
                        <div class="row mb-2">
                            <div class="col-md-4">
                                Kewarganegaraan
                            </div>
                            <div class="col-md-8">
                                : <strong>{{ $penduduk->anggota->warga_negara }}</strong>
                            </div>
                        </div>
                        <div class="row mb-2">
                            <div class="col-md-4">
                                Jenis Mutasi
                            </div>
                            <div class="col-md-8">
                                : <strong>{{ $penduduk->jenis }}</strong>
                            </div>
                        </div>
                        @if($penduduk->jenis == 'Lahir')
                        <div class="row mb-2">
                            <div class="col-md-4">
                                Ayah
                            </div>
                            <div class="col-md-8">
                                : <strong>{{ ($penduduk->anggota->ayah != null) ? $penduduk->anggota->ayah->nama : '' }}</strong>
                            </div>
                        </div>
                        <div class="row mb-2">
                            <div class="col-md-4">
                                Ibu
                            </div>
                            <div class="col-md-8">
                                : <strong>{{ ($penduduk->anggota->ibu != null) ? $penduduk->anggota->ibu->nama : '' }}</strong>
                            </div>
                        </div>
                        @endif
                        <div class="row mb-2">
                            <div class="col-md-4">
                                Tanggal Kejadian
                            </div>
                            <div class="col-md-8">
                                : <strong>{{ date_format(date_create($penduduk->tanggal), 'd-m-Y') }}</strong>
                            </div>
                        </div>
                        <div class="row mb-2">
                            <div class="col-md-4">
                                Keterangan
                            </div>
                            <div class="col-md-8">
                                : <strong>{{ $penduduk->keternagan }}</strong>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <a href="{{ route('pindah-masuk.edit', $penduduk->id) }}" title="Edit" class="btn btn-warning"><i class="nc-icon nc-ruler-pencil"></i> Ubah Data</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection